spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
  cloud:
    gcp:
      storage:
        bucket: ${GCP_DEV_BUCKET_NAME}

management:
  endpoints:
    web:
      exposure:
        include: "health"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false