-- Drop tables in reverse dependency order
DROP TABLE IF EXISTS student_enrollments CASCADE;
DROP TABLE IF EXISTS subject_enrollment_requests CASCADE;
DROP TABLE IF EXISTS volunteer_applications CASCADE;
DROP TABLE IF EXISTS student_registration_requests CASCADE;
DROP TABLE IF EXISTS absence_requests CASCADE;
DROP TABLE IF EXISTS lesson_exchange_proposals CASCADE;
DROP TABLE IF EXISTS lesson_exchange_requests CASCADE;
DROP TABLE IF EXISTS purchase_request_receipts CASCADE;
DROP TABLE IF EXISTS purchase_requests_items CASCADE;
DROP TABLE IF EXISTS purchase_requests CASCADE;
DROP TABLE IF EXISTS subject_exchange_requests CASCADE;
DROP TABLE IF EXISTS post_attachments CASCADE;
DROP TABLE IF EXISTS post_files CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS channels CASCADE;
DROP TABLE IF EXISTS daily_teacher_attendances CASCADE;
DROP TABLE IF EXISTS daily_student_attendances CASCADE;
DROP TABLE IF EXISTS daily_schedules CASCADE;
DROP TABLE IF EXISTS lessons CASCADE;
DROP TABLE IF EXISTS subjects CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS classrooms CASCADE;
DROP TABLE IF EXISTS refresh_tokens CASCADE;
DROP TABLE IF EXISTS user_credentials CASCADE;
DROP TABLE IF EXISTS push_subscriptions CASCADE;
DROP TABLE IF EXISTS user_permissions CASCADE;
DROP TABLE IF EXISTS department_permissions CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS files CASCADE;


CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL,
    primary_email VARCHAR(100) UNIQUE,
    phone_number VARCHAR(20),
    profile_image_url VARCHAR(255),
    department_id BIGINT REFERENCES departments(id),
    role VARCHAR(20) NOT NULL DEFAULT 'GUEST',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_department_id ON users(department_id);
CREATE INDEX idx_users_role ON users(role);


-- User credentials table
CREATE TABLE user_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(50) NOT NULL,
    provider_user_id VARCHAR(150),
    credential_email VARCHAR(100),
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    password_hash VARCHAR(512),
    last_login_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_user_credentials_provider_email UNIQUE (provider, credential_email),
    CONSTRAINT uq_user_credentials_provider_user_id UNIQUE (provider, provider_user_id)
);

CREATE INDEX idx_user_credentials_user_id ON user_credentials(user_id);
CREATE INDEX idx_user_credentials_credential_email ON user_credentials(credential_email);

-- Refresh tokens table
CREATE TABLE refresh_tokens (
    token VARCHAR(500) PRIMARY KEY,
    credential_id BIGINT NOT NULL REFERENCES user_credentials(id) ON DELETE CASCADE,
    expiry_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_refresh_tokens_credential_id ON refresh_tokens(credential_id);
CREATE INDEX idx_refresh_tokens_expiry_date ON refresh_tokens(expiry_date);

CREATE TABLE department_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL,
    permission_code VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE,
    CONSTRAINT uk_department_permission UNIQUE (department_id, permission_code)
);

CREATE INDEX idx_department_permissions_department_id ON department_permissions(department_id);
CREATE INDEX idx_department_permissions_code ON department_permissions(permission_code);

CREATE TABLE user_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    permission_code VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_user_permission UNIQUE (user_id, permission_code)
);

CREATE INDEX idx_user_permissions_user_id ON user_permissions(user_id);
CREATE INDEX idx_user_permissions_code ON user_permissions(permission_code);

CREATE TABLE push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(1024) NOT NULL,
    device_type VARCHAR(20) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    subscribed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    unsubscribed_at TIMESTAMP,
    last_used_at TIMESTAMP,
    failure_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_push_subscriptions_token UNIQUE (token)
);

CREATE INDEX idx_push_subscriptions_user_id ON push_subscriptions(user_id);
CREATE INDEX idx_push_subscriptions_user_active ON push_subscriptions(user_id, is_active);

CREATE TABLE classrooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    type VARCHAR(20) NOT NULL,
    description TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    phone_number VARCHAR(20),
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ENROLLED',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (class_id) REFERENCES classrooms(id)
);

CREATE TABLE subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT NOT NULL,
    teacher_id BIGINT,
    name VARCHAR(50) NOT NULL,
    start_at DATE NOT NULL,
    end_at DATE NOT NULL,
    day_of_week VARCHAR(20) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    period INTEGER NOT NULL,
    teacher_assigned_at TIMESTAMP,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (class_id) REFERENCES classrooms(id),
    FOREIGN KEY (teacher_id) REFERENCES users(id)
);

CREATE INDEX idx_subjects_class_id ON subjects(class_id);
CREATE INDEX idx_subjects_teacher_id ON subjects(teacher_id);

CREATE TABLE lessons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    period INT NOT NULL DEFAULT 1,
    date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    note TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (subject_id) REFERENCES subjects(id),
    FOREIGN KEY (teacher_id) REFERENCES users(id)
);

CREATE INDEX idx_lessons_subject_id ON lessons(subject_id);
CREATE INDEX idx_lessons_teacher_id ON lessons(teacher_id);
CREATE INDEX idx_lessons_date ON lessons(date);

CREATE TABLE daily_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classroom_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    lesson_date DATE NOT NULL,
    activity_start_time TIME,
    activity_end_time TIME,
    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    resident_registration_number_prefix VARCHAR(6),
    personal_info_consent BOOLEAN NOT NULL DEFAULT FALSE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (classroom_id) REFERENCES classrooms(id),
    FOREIGN KEY (teacher_id) REFERENCES users(id),
    CONSTRAINT uk_daily_schedule_classroom_date UNIQUE (classroom_id, lesson_date)
);

CREATE TABLE daily_teacher_attendances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_schedule_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ABSENT',
    volunteer_service_minutes INTEGER,
    attended_at TIMESTAMP,
    latitude DECIMAL(10, 7),
    longitude DECIMAL(10, 7),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (daily_schedule_id) REFERENCES daily_schedules(id),
    CONSTRAINT uk_teacher_attendance_daily_schedule UNIQUE (daily_schedule_id)
);

CREATE TABLE daily_student_attendances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_schedule_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ABSENT',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (daily_schedule_id) REFERENCES daily_schedules(id),
    FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT uk_daily_student_attendance_schedule_student UNIQUE (daily_schedule_id, student_id)
);

CREATE TABLE absence_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_schedule_id BIGINT NOT NULL,
    requested_by BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    reason TEXT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL,
    approval_at TIMESTAMP,
    approval_by BIGINT,
    note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (daily_schedule_id) REFERENCES daily_schedules(id),
    FOREIGN KEY (requested_by) REFERENCES users(id),
    FOREIGN KEY (approval_by) REFERENCES users(id)
);

CREATE INDEX idx_absence_requests_daily_schedule_id ON absence_requests(daily_schedule_id);
CREATE INDEX idx_absence_requests_requested_by ON absence_requests(requested_by);

CREATE TABLE lesson_exchange_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_schedule_id BIGINT NOT NULL,
    lesson_date DATE NOT NULL,
    requested_by BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    classroom_name_snapshot VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    processed_at TIMESTAMP,
    processed_by BIGINT,
    completed_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    rejection_note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (daily_schedule_id) REFERENCES daily_schedules(id),
    FOREIGN KEY (requested_by) REFERENCES users(id),
    FOREIGN KEY (processed_by) REFERENCES users(id)
);

CREATE TABLE lesson_exchange_proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL,
    proposed_by BIGINT NOT NULL,
    proposal_type VARCHAR(20) NOT NULL,
    daily_schedule_id BIGINT,
    lesson_date DATE,
    content TEXT NOT NULL,
    classroom_name_snapshot VARCHAR(255),
    status VARCHAR(20) NOT NULL,
    accepted_at TIMESTAMP,
    withdrawn_at TIMESTAMP,
    closed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (request_id) REFERENCES lesson_exchange_requests(id),
    FOREIGN KEY (daily_schedule_id) REFERENCES daily_schedules(id),
    FOREIGN KEY (proposed_by) REFERENCES users(id)
);

CREATE INDEX idx_lesson_exchange_requests_lesson_date ON lesson_exchange_requests(lesson_date);
CREATE INDEX idx_lesson_exchange_requests_requested_by ON lesson_exchange_requests(requested_by);

CREATE TABLE purchase_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classroom_id BIGINT NOT NULL,
    requested_by BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    total_price BIGINT,
    advance_payment_requested_amount BIGINT,
    advance_payment_approved_amount BIGINT,
    status VARCHAR(20) NOT NULL,
    approval_at TIMESTAMP,
    approval_by BIGINT,
    purchased_at TIMESTAMP,
    note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (classroom_id) REFERENCES classrooms(id),
    FOREIGN KEY (requested_by) REFERENCES users(id),
    FOREIGN KEY (approval_by) REFERENCES users(id)
);

CREATE INDEX idx_purchase_requests_classroom_id ON purchase_requests(classroom_id);
CREATE INDEX idx_purchase_requests_requested_by ON purchase_requests(requested_by);

CREATE TABLE files (
    id            UUID PRIMARY KEY,
    storage_key   VARCHAR(500) NOT NULL,
    bucket        VARCHAR(100) NOT NULL,
    public_url    VARCHAR(1000) NOT NULL,
    original_name VARCHAR(255),
    content_type  VARCHAR(100) NOT NULL,
    file_size     BIGINT,
    ext           VARCHAR(20)  NOT NULL,
    is_deleted    BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at    TIMESTAMP,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_files_public_url ON files(public_url);

CREATE TABLE purchase_requests_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_request_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    reason TEXT,
    expected_price BIGINT,
    actual_price BIGINT,
    FOREIGN KEY (purchase_request_id) REFERENCES purchase_requests(id)
);

CREATE TABLE purchase_request_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_request_id BIGINT NOT NULL,
    file_id UUID NOT NULL,
    FOREIGN KEY (purchase_request_id) REFERENCES purchase_requests(id),
    FOREIGN KEY (file_id) REFERENCES files(id)
);

CREATE TABLE channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    channel_type VARCHAR(20) NOT NULL,
    binding_type VARCHAR(20) NOT NULL,
    ref_id BIGINT,
    access_level VARCHAR(30) NOT NULL,
    allow_guest_read BOOLEAN NOT NULL DEFAULT FALSE,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    last_posted_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_channels_channel_type_ref_id ON channels(channel_type, ref_id);
CREATE INDEX idx_channels_binding_type ON channels(binding_type);
CREATE INDEX idx_channels_is_active ON channels(is_active);

CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content_html TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED',
    is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
    allow_comment BOOLEAN NOT NULL DEFAULT FALSE,
    thumbnail_url VARCHAR(500),
    expires_at TIMESTAMP,
    view_count BIGINT NOT NULL DEFAULT 0,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (channel_id) REFERENCES channels(id),
    FOREIGN KEY (author_id) REFERENCES users(id)
);

CREATE INDEX idx_posts_channel_id ON posts(channel_id);
CREATE INDEX idx_posts_author_id ON posts(author_id);
CREATE INDEX idx_posts_status ON posts(status);
CREATE INDEX idx_posts_expires_at ON posts(expires_at);
CREATE INDEX idx_posts_created_at ON posts(created_at);

CREATE TABLE post_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    file_id UUID NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    FOREIGN KEY (file_id) REFERENCES files(id),
    CONSTRAINT uk_post_file UNIQUE (post_id, file_id)
);

CREATE INDEX idx_post_files_post_id ON post_files(post_id);
CREATE INDEX idx_post_files_file_id ON post_files(file_id);

CREATE TABLE post_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    file_id UUID NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    FOREIGN KEY (file_id) REFERENCES files(id),
    CONSTRAINT uk_post_attachment UNIQUE (post_id, file_id)
);

CREATE INDEX idx_post_attachments_post_id ON post_attachments(post_id);
CREATE INDEX idx_post_attachments_file_id ON post_attachments(file_id);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    parent_comment_id BIGINT,
    content TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES users(id),
    FOREIGN KEY (parent_comment_id) REFERENCES comments(id) ON DELETE CASCADE
);

CREATE INDEX idx_comments_post_id ON comments(post_id);
CREATE INDEX idx_comments_author_id ON comments(author_id);
CREATE INDEX idx_comments_parent_comment_id ON comments(parent_comment_id);
CREATE INDEX idx_comments_created_at ON comments(created_at);

-- =====================================================================
-- Request Forms
-- =====================================================================

-- 봉사 신청: 기존 과목에 교사로 지원하거나 새 과목을 제안
-- application_type: EXISTING_SUBJECT | NEW_SUBJECT
-- 승인 시: 신청자가 TEACHER가 됨, NEW_SUBJECT면 subjects 레코드 생성
CREATE TABLE volunteer_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_id BIGINT NOT NULL,
    application_type VARCHAR(20) NOT NULL,

    -- EXISTING_SUBJECT 선택 시
    subject_id BIGINT,

    -- NEW_SUBJECT 제안 시 (classroom_id는 관리자가 승인 시 배정)
    proposed_classroom_id BIGINT,
    proposed_name VARCHAR(50),
    proposed_start_at DATE,
    proposed_end_at DATE,
    proposed_times INTEGER,
    proposed_day_of_week VARCHAR(20),
    proposed_start_time TIME,
    proposed_end_time TIME,
    proposed_period INTEGER,
    proposed_description TEXT,

    motivation TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    reviewed_by BIGINT,
    reviewed_at TIMESTAMP,
    review_note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (applicant_id) REFERENCES users(id),
    FOREIGN KEY (subject_id) REFERENCES subjects(id),
    FOREIGN KEY (proposed_classroom_id) REFERENCES classrooms(id),
    FOREIGN KEY (reviewed_by) REFERENCES users(id)
);

CREATE INDEX idx_volunteer_applications_applicant_id ON volunteer_applications(applicant_id);
CREATE INDEX idx_volunteer_applications_status ON volunteer_applications(status);

-- 학생 등록 신청: 야학 학생이 되고 싶은 사람 (user 계정 불필요)
-- 승인 시: students 레코드 생성 후 student_id 연결
CREATE TABLE student_registration_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    phone_number VARCHAR(20),
    birth_date DATE,
    message TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    reviewed_by BIGINT,
    reviewed_at TIMESTAMP,
    review_note TEXT,
    student_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (reviewed_by) REFERENCES users(id),
    FOREIGN KEY (student_id) REFERENCES students(id)
);

CREATE INDEX idx_student_registration_requests_status ON student_registration_requests(status);

-- 수강 등록 신청: 등록된 학생이 특정 과목 수강 신청
-- 승인 시: student_enrollments 레코드 생성
CREATE TABLE subject_enrollment_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    message TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    reviewed_by BIGINT,
    reviewed_at TIMESTAMP,
    review_note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES students(id),
    FOREIGN KEY (subject_id) REFERENCES subjects(id),
    FOREIGN KEY (reviewed_by) REFERENCES users(id)
);

CREATE INDEX idx_subject_enrollment_requests_student_id ON subject_enrollment_requests(student_id);
CREATE INDEX idx_subject_enrollment_requests_subject_id ON subject_enrollment_requests(subject_id);
CREATE INDEX idx_subject_enrollment_requests_status ON subject_enrollment_requests(status);

-- 수강 등록: subject_enrollment_requests 승인 후 생성
-- 한 학생이 한 과목에 중복 등록 불가
CREATE TABLE student_enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    enrollment_request_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    enrolled_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    withdrawn_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES students(id),
    FOREIGN KEY (subject_id) REFERENCES subjects(id),
    FOREIGN KEY (enrollment_request_id) REFERENCES subject_enrollment_requests(id),
    CONSTRAINT uk_student_enrollment UNIQUE (student_id, subject_id)
);

CREATE INDEX idx_student_enrollments_student_id ON student_enrollments(student_id);
CREATE INDEX idx_student_enrollments_subject_id ON student_enrollments(subject_id);
