apiVersion: 1

datasources:
  - name: Google Cloud Monitoring
    uid: gcp-monitoring
    type: stackdriver
    access: proxy
    isDefault: true
    jsonData:
      authenticationType: gce
      universeDomain: googleapis.com
