-- Drop tables in reverse dependency order
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS teacher_applications CASCADE;
DROP TABLE IF EXISTS absence_requests CASCADE;
DROP TABLE IF EXISTS lesson_exchange_proposals CASCADE;
DROP TABLE IF EXISTS lesson_exchange_requests CASCADE;
DROP TABLE IF EXISTS purchase_request_receipts CASCADE;
DROP TABLE IF EXISTS purchase_request_payment_transaction_item_names CASCADE;
DROP TABLE IF EXISTS purchase_request_payment_transactions CASCADE;
DROP TABLE IF EXISTS purchase_requests_items CASCADE;
DROP TABLE IF EXISTS purchase_requests CASCADE;
DROP TABLE IF EXISTS vendor_balance_histories CASCADE;
DROP TABLE IF EXISTS vendors CASCADE;
DROP TABLE IF EXISTS subject_exchange_requests CASCADE;
DROP TABLE IF EXISTS post_attachments CASCADE;
DROP TABLE IF EXISTS post_files CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS meeting_absence_reports CASCADE;
DROP TABLE IF EXISTS meeting_records CASCADE;
DROP TABLE IF EXISTS channels CASCADE;
DROP TABLE IF EXISTS daily_teacher_attendances CASCADE;
DROP TABLE IF EXISTS daily_student_attendances CASCADE;
DROP TABLE IF EXISTS daily_schedules CASCADE;
DROP TABLE IF EXISTS lessons CASCADE;
DROP TABLE IF EXISTS subjects CASCADE;
DROP TABLE IF EXISTS student_classrooms CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS site_history_photos CASCADE;
DROP TABLE IF EXISTS site_histories CASCADE;
DROP TABLE IF EXISTS site_content_items CASCADE;
DROP TABLE IF EXISTS site_contents CASCADE;
DROP TABLE IF EXISTS classrooms CASCADE;
DROP TABLE IF EXISTS refresh_tokens CASCADE;
DROP TABLE IF EXISTS user_credentials CASCADE;
DROP TABLE IF EXISTS user_permissions CASCADE;
DROP TABLE IF EXISTS department_permissions CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS files CASCADE;


CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    primary_email VARCHAR(100) UNIQUE,
    phone_number VARCHAR(20),
    profile_image_url VARCHAR(255),
    department_id BIGINT REFERENCES departments(id),
    classroom_id BIGINT,
    resident_registration_number_prefix VARCHAR(6),
    teacher_start_at DATE,
    teacher_end_at DATE,
    role VARCHAR(20) NOT NULL DEFAULT 'GUEST',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_department_id ON users(department_id);
CREATE INDEX idx_users_role ON users(role);

CREATE TABLE user_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(50) NOT NULL,
    provider_user_id VARCHAR(150),
    credential_email VARCHAR(100),
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    password_hash VARCHAR(512),
    last_login_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_user_credentials_provider_email UNIQUE (provider, credential_email),
    CONSTRAINT uq_user_credentials_provider_user_id UNIQUE (provider, provider_user_id)
);

CREATE INDEX idx_user_credentials_user_id ON user_credentials(user_id);
CREATE INDEX idx_user_credentials_credential_email ON user_credentials(credential_email);

CREATE TABLE refresh_tokens (
    token VARCHAR(500) PRIMARY KEY,
    credential_id BIGINT NOT NULL REFERENCES user_credentials(id) ON DELETE CASCADE,
    expiry_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_refresh_tokens_credential_id ON refresh_tokens(credential_id);
CREATE INDEX idx_refresh_tokens_expiry_date ON refresh_tokens(expiry_date);

CREATE TABLE department_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL,
    permission_code VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE,
    CONSTRAINT uk_department_permission UNIQUE (department_id, permission_code)
);

CREATE INDEX idx_department_permissions_department_id ON department_permissions(department_id);
CREATE INDEX idx_department_permissions_code ON department_permissions(permission_code);

CREATE TABLE user_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    permission_code VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_user_permission UNIQUE (user_id, permission_code)
);

CREATE INDEX idx_user_permissions_user_id ON user_permissions(user_id);
CREATE INDEX idx_user_permissions_code ON user_permissions(permission_code);

CREATE TABLE classrooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    type VARCHAR(20) NOT NULL,
    description TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE site_contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type VARCHAR(30) NOT NULL,
    ref_id BIGINT,
    title VARCHAR(120) NOT NULL,
    name VARCHAR(80),
    content_group VARCHAR(30),
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_site_contents_type_sort ON site_contents(content_type, sort_order, id);
CREATE INDEX idx_site_contents_ref ON site_contents(content_type, ref_id);

CREATE TABLE site_content_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_content_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (site_content_id) REFERENCES site_contents(id) ON DELETE CASCADE
);

CREATE INDEX idx_site_content_items_parent_sort
    ON site_content_items(site_content_id, sort_order, id);

CREATE TABLE site_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    detail TEXT,
    link_label VARCHAR(120),
    link_href TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_site_histories_sort ON site_histories(sort_order, id);

CREATE TABLE site_history_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    history_id BIGINT NOT NULL,
    file_id UUID,
    src TEXT NOT NULL,
    alt VARCHAR(255),
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (history_id) REFERENCES site_histories(id) ON DELETE CASCADE
);

CREATE INDEX idx_site_history_photos_parent_sort
    ON site_history_photos(history_id, sort_order, id);
CREATE INDEX idx_site_history_photos_file_id ON site_history_photos(file_id);

CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    phone_number VARCHAR(20),
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ENROLLED',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE student_classrooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    classroom_id BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    FOREIGN KEY (classroom_id) REFERENCES classrooms(id),
    CONSTRAINT uk_student_classroom UNIQUE (student_id, classroom_id)
);

CREATE TABLE subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT NOT NULL,
    teacher_id BIGINT,
    name VARCHAR(50) NOT NULL,
    start_at DATE NOT NULL,
    end_at DATE NOT NULL,
    day_of_week VARCHAR(20) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    period INTEGER NOT NULL,
    teacher_assigned_at TIMESTAMP,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (class_id) REFERENCES classrooms(id),
    FOREIGN KEY (teacher_id) REFERENCES users(id)
);

CREATE INDEX idx_subjects_class_id ON subjects(class_id);
CREATE INDEX idx_subjects_teacher_id ON subjects(teacher_id);

CREATE TABLE teacher_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_id BIGINT NOT NULL,
    applicant_name VARCHAR(50) NOT NULL,
    applicant_phone_number VARCHAR(20) NOT NULL,
    applicant_email VARCHAR(100) NOT NULL,
    birth_date DATE NOT NULL,
    address VARCHAR(255) NOT NULL,
    education_and_major VARCHAR(255) NOT NULL,
    preferred_subject_id BIGINT NOT NULL,
    motivation TEXT NOT NULL,
    desired_teacher_image TEXT NOT NULL,
    meaning_of_sharing TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    reviewed_at TIMESTAMP,
    reviewed_by BIGINT,
    review_note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (applicant_id) REFERENCES users(id),
    FOREIGN KEY (preferred_subject_id) REFERENCES subjects(id),
    FOREIGN KEY (reviewed_by) REFERENCES users(id)
);

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description TEXT,
    event_date DATE NOT NULL,
    start_time TIME,
    end_time TIME,
    created_by_id BIGINT NOT NULL,
    updated_by_id BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (updated_by_id) REFERENCES users(id)
);

CREATE TABLE lessons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    period INT NOT NULL DEFAULT 1,
    date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    note TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (subject_id) REFERENCES subjects(id),
    FOREIGN KEY (teacher_id) REFERENCES users(id)
);

CREATE INDEX idx_lessons_subject_id ON lessons(subject_id);
CREATE INDEX idx_lessons_teacher_id ON lessons(teacher_id);
CREATE INDEX idx_lessons_date ON lessons(date);

CREATE TABLE daily_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classroom_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    lesson_date DATE NOT NULL,
    activity_start_time TIME,
    activity_end_time TIME,
    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    resident_registration_number_prefix VARCHAR(6),
    personal_info_consent BOOLEAN NOT NULL DEFAULT FALSE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (classroom_id) REFERENCES classrooms(id),
    FOREIGN KEY (teacher_id) REFERENCES users(id),
    CONSTRAINT uk_daily_schedule_classroom_date UNIQUE (classroom_id, lesson_date)
);

CREATE TABLE daily_teacher_attendances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_schedule_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ABSENT',
    volunteer_service_minutes INTEGER,
    attended_at TIMESTAMP,
    latitude DECIMAL(10, 7),
    longitude DECIMAL(10, 7),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (daily_schedule_id) REFERENCES daily_schedules(id),
    CONSTRAINT uk_teacher_attendance_daily_schedule UNIQUE (daily_schedule_id)
);

CREATE TABLE daily_student_attendances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_schedule_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ABSENT',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (daily_schedule_id) REFERENCES daily_schedules(id),
    FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT uk_daily_student_attendance_schedule_student UNIQUE (daily_schedule_id, student_id)
);

CREATE TABLE absence_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_schedule_id BIGINT NOT NULL,
    requested_by BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    reason TEXT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL,
    approval_at TIMESTAMP,
    approval_by BIGINT,
    note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (daily_schedule_id) REFERENCES daily_schedules(id),
    FOREIGN KEY (requested_by) REFERENCES users(id),
    FOREIGN KEY (approval_by) REFERENCES users(id)
);

CREATE INDEX idx_absence_requests_daily_schedule_id ON absence_requests(daily_schedule_id);
CREATE INDEX idx_absence_requests_requested_by ON absence_requests(requested_by);

CREATE TABLE lesson_exchange_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_schedule_id BIGINT NOT NULL,
    lesson_date DATE NOT NULL,
    requested_by BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    classroom_name_snapshot VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    processed_at TIMESTAMP,
    processed_by BIGINT,
    completed_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    rejection_note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (daily_schedule_id) REFERENCES daily_schedules(id),
    FOREIGN KEY (requested_by) REFERENCES users(id),
    FOREIGN KEY (processed_by) REFERENCES users(id)
);

CREATE TABLE lesson_exchange_proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL,
    proposed_by BIGINT NOT NULL,
    proposal_type VARCHAR(20) NOT NULL,
    daily_schedule_id BIGINT,
    lesson_date DATE,
    content TEXT NOT NULL,
    classroom_name_snapshot VARCHAR(255),
    status VARCHAR(20) NOT NULL,
    accepted_at TIMESTAMP,
    withdrawn_at TIMESTAMP,
    closed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (request_id) REFERENCES lesson_exchange_requests(id),
    FOREIGN KEY (daily_schedule_id) REFERENCES daily_schedules(id),
    FOREIGN KEY (proposed_by) REFERENCES users(id)
);

CREATE INDEX idx_lesson_exchange_requests_lesson_date ON lesson_exchange_requests(lesson_date);
CREATE INDEX idx_lesson_exchange_requests_requested_by ON lesson_exchange_requests(requested_by);

CREATE TABLE vendors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    balance BIGINT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE purchase_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classroom_id BIGINT NOT NULL,
    requested_by BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    total_price BIGINT,
    status VARCHAR(20) NOT NULL,
    approval_at TIMESTAMP,
    approval_by BIGINT,
    purchased_at TIMESTAMP,
    note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (classroom_id) REFERENCES classrooms(id),
    FOREIGN KEY (requested_by) REFERENCES users(id),
    FOREIGN KEY (approval_by) REFERENCES users(id)
);

CREATE INDEX idx_purchase_requests_classroom_id ON purchase_requests(classroom_id);
CREATE INDEX idx_purchase_requests_requested_by ON purchase_requests(requested_by);

CREATE TABLE files (
    id            UUID DEFAULT random_uuid() PRIMARY KEY,
    storage_key   VARCHAR(500) NOT NULL,
    bucket        VARCHAR(100) NOT NULL,
    public_url    VARCHAR(1000) NOT NULL,
    original_name VARCHAR(255),
    content_type  VARCHAR(100) NOT NULL,
    file_size     BIGINT,
    ext           VARCHAR(20)  NOT NULL,
    is_google_drive BOOLEAN NOT NULL DEFAULT FALSE,
    is_deleted    BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at    TIMESTAMP,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_files_public_url ON files(public_url);

CREATE TABLE purchase_requests_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_request_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    reason TEXT,
    quantity INTEGER NOT NULL,
    payment_type VARCHAR(20) NOT NULL,
    FOREIGN KEY (purchase_request_id) REFERENCES purchase_requests(id)
);

CREATE TABLE purchase_request_payment_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_request_id BIGINT NOT NULL,
    vendor_id BIGINT NOT NULL,
    amount BIGINT NOT NULL,
    receipt_file_id UUID,
    FOREIGN KEY (purchase_request_id) REFERENCES purchase_requests(id),
    FOREIGN KEY (vendor_id) REFERENCES vendors(id),
    FOREIGN KEY (receipt_file_id) REFERENCES files(id)
);

CREATE TABLE purchase_request_payment_transaction_item_names (
    transaction_id BIGINT NOT NULL,
    sort_order INTEGER NOT NULL,
    item_name VARCHAR(255) NOT NULL,
    FOREIGN KEY (transaction_id) REFERENCES purchase_request_payment_transactions(id)
);

CREATE TABLE vendor_balance_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    amount BIGINT NOT NULL,
    balance_after BIGINT NOT NULL,
    memo TEXT,
    receipt_file_id UUID,
    purchase_request_id BIGINT,
    created_by BIGINT NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (vendor_id) REFERENCES vendors(id),
    FOREIGN KEY (receipt_file_id) REFERENCES files(id),
    FOREIGN KEY (purchase_request_id) REFERENCES purchase_requests(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    channel_type VARCHAR(20) NOT NULL,
    binding_type VARCHAR(20) NOT NULL,
    ref_id BIGINT,
    access_level VARCHAR(30) NOT NULL,
    allow_guest_read BOOLEAN NOT NULL DEFAULT FALSE,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    last_posted_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_channels_channel_type_ref_id ON channels(channel_type, ref_id);
CREATE INDEX idx_channels_binding_type ON channels(binding_type);
CREATE INDEX idx_channels_is_active ON channels(is_active);

CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content_html TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED',
    is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
    allow_comment BOOLEAN NOT NULL DEFAULT FALSE,
    thumbnail_url VARCHAR(500),
    expires_at TIMESTAMP,
    view_count BIGINT NOT NULL DEFAULT 0,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (channel_id) REFERENCES channels(id),
    FOREIGN KEY (author_id) REFERENCES users(id)
);

CREATE INDEX idx_posts_channel_id ON posts(channel_id);
CREATE INDEX idx_posts_author_id ON posts(author_id);
CREATE INDEX idx_posts_status ON posts(status);
CREATE INDEX idx_posts_expires_at ON posts(expires_at);
CREATE INDEX idx_posts_created_at ON posts(created_at);

CREATE TABLE post_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    file_id UUID NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    FOREIGN KEY (file_id) REFERENCES files(id),
    CONSTRAINT uk_post_file UNIQUE (post_id, file_id)
);

CREATE INDEX idx_post_files_post_id ON post_files(post_id);
CREATE INDEX idx_post_files_file_id ON post_files(file_id);

CREATE TABLE post_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    file_id UUID NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    FOREIGN KEY (file_id) REFERENCES files(id),
    CONSTRAINT uk_post_attachment UNIQUE (post_id, file_id)
);

CREATE INDEX idx_post_attachments_post_id ON post_attachments(post_id);
CREATE INDEX idx_post_attachments_file_id ON post_attachments(file_id);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    parent_comment_id BIGINT,
    content TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES users(id),
    FOREIGN KEY (parent_comment_id) REFERENCES comments(id) ON DELETE CASCADE
);

CREATE INDEX idx_comments_post_id ON comments(post_id);
CREATE INDEX idx_comments_author_id ON comments(author_id);
CREATE INDEX idx_comments_parent_comment_id ON comments(parent_comment_id);
CREATE INDEX idx_comments_created_at ON comments(created_at);

CREATE TABLE meeting_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    agenda TEXT NOT NULL,
    discussion TEXT,
    suggestion TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'BEFORE_MEETING',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    view_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (author_id) REFERENCES users(id),
    CONSTRAINT chk_meeting_records_status CHECK (status IN ('BEFORE_MEETING', 'AFTER_MEETING'))
);

CREATE INDEX idx_meeting_records_author_id ON meeting_records(author_id);
CREATE INDEX idx_meeting_records_status ON meeting_records(status);
CREATE INDEX idx_meeting_records_created_at ON meeting_records(created_at);
CREATE INDEX idx_meeting_records_is_deleted ON meeting_records(is_deleted);

CREATE TABLE meeting_absence_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_record_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    reason TEXT NOT NULL,
    opinion TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (meeting_record_id) REFERENCES meeting_records(id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES users(id)
);

CREATE INDEX idx_meeting_absence_reports_meeting_record_id ON meeting_absence_reports(meeting_record_id);
CREATE INDEX idx_meeting_absence_reports_author_id ON meeting_absence_reports(author_id);
CREATE INDEX idx_meeting_absence_reports_created_at ON meeting_absence_reports(created_at);
CREATE INDEX idx_meeting_absence_reports_is_deleted ON meeting_absence_reports(is_deleted);
