- targets:
    - gjlearn-dev-app.tail523ef0.ts.net:9100
  labels:
    project: gjlearn
    env: dev
    service: app
    role: node-exporter
    instance_name: gjlearn-dev-app
    domain: dev.geumjeongschool.com

- targets:
    - gjlearn-dev-db.tail523ef0.ts.net:9100
  labels:
    project: gjlearn
    env: dev
    service: db
    role: node-exporter
    instance_name: gjlearn-dev-db
    domain: dev.geumjeongschool.com
