ALTER TABLE vendors
    ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

ALTER TABLE vendor_balance_histories
    ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

ALTER TABLE purchase_requests_items
    ADD COLUMN IF NOT EXISTS quantity INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS payment_type VARCHAR(20) NOT NULL DEFAULT 'ACTUAL';

ALTER TABLE purchase_requests_items
    DROP COLUMN IF EXISTS price,
    DROP COLUMN IF EXISTS expected_price,
    DROP COLUMN IF EXISTS actual_price,
    DROP COLUMN IF EXISTS receipt_file_id;

ALTER TABLE purchase_requests
    ALTER COLUMN total_price SET DEFAULT 0;

UPDATE purchase_requests SET total_price = 0 WHERE total_price IS NULL;

ALTER TABLE purchase_requests
    ALTER COLUMN total_price SET NOT NULL,
    DROP COLUMN IF EXISTS payment_method,
    DROP COLUMN IF EXISTS vendor_id,
    DROP COLUMN IF EXISTS advance_payment_requested_amount,
    DROP COLUMN IF EXISTS advance_payment_approved_amount;

CREATE TABLE IF NOT EXISTS purchase_request_payment_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_request_id BIGINT NOT NULL,
    vendor_id BIGINT NOT NULL,
    amount BIGINT NOT NULL,
    receipt_file_id UUID,
    FOREIGN KEY (purchase_request_id) REFERENCES purchase_requests(id),
    FOREIGN KEY (vendor_id) REFERENCES vendors(id),
    FOREIGN KEY (receipt_file_id) REFERENCES files(id)
);

CREATE TABLE IF NOT EXISTS purchase_request_payment_transaction_item_names (
    transaction_id BIGINT NOT NULL,
    sort_order INTEGER NOT NULL,
    item_name VARCHAR(255) NOT NULL,
    FOREIGN KEY (transaction_id) REFERENCES purchase_request_payment_transactions(id)
);
