CREATE TABLE purchase_request_proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_request_id BIGINT NOT NULL UNIQUE,
    overview TEXT,
    policy_project VARCHAR(255),
    unit_project VARCHAR(255),
    detail_project VARCHAR(255),
    request_department_id BIGINT,
    proposal_date DATE,
    proposal_amount BIGINT,
    payment_account VARCHAR(40),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (purchase_request_id) REFERENCES purchase_requests(id),
    FOREIGN KEY (request_department_id) REFERENCES departments(id),
    CONSTRAINT ck_purchase_request_proposal_amount
        CHECK (proposal_amount IS NULL OR proposal_amount >= 0)
);

CREATE INDEX idx_purchase_request_proposals_account_date_id
    ON purchase_request_proposals(payment_account, proposal_date, id);

CREATE TABLE purchase_request_proposal_budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id BIGINT NOT NULL UNIQUE,
    item_category VARCHAR(40),
    custom_item_category VARCHAR(255),
    calculation_detail VARCHAR(60),
    custom_calculation_detail VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (proposal_id) REFERENCES purchase_request_proposals(id)
);

CREATE TABLE purchase_request_proposal_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id BIGINT NOT NULL,
    content TEXT,
    specification VARCHAR(255),
    quantity INTEGER,
    estimated_unit_price BIGINT,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (proposal_id) REFERENCES purchase_request_proposals(id),
    CONSTRAINT ck_purchase_request_proposal_item_quantity
        CHECK (quantity IS NULL OR quantity >= 1),
    CONSTRAINT ck_purchase_request_proposal_item_unit_price
        CHECK (estimated_unit_price IS NULL OR estimated_unit_price >= 0)
);

CREATE INDEX idx_purchase_request_proposal_items_proposal_order
    ON purchase_request_proposal_items(proposal_id, sort_order);

CREATE TABLE purchase_request_proposal_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id BIGINT NOT NULL,
    file_id UUID NOT NULL,
    sort_order INTEGER NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (proposal_id) REFERENCES purchase_request_proposals(id),
    FOREIGN KEY (file_id) REFERENCES files(id)
);

CREATE INDEX idx_purchase_request_proposal_receipts_proposal_active
    ON purchase_request_proposal_receipts(proposal_id, is_deleted);

CREATE INDEX idx_purchase_request_proposal_receipts_file_id
    ON purchase_request_proposal_receipts(file_id);
