ALTER TABLE purchase_request_proposals
    ADD COLUMN proposal_title VARCHAR(255),
    ADD COLUMN resolution_title VARCHAR(255),
    ADD COLUMN completion_date DATE;

CREATE TABLE purchase_request_proposal_approval_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id BIGINT NOT NULL,
    line_type VARCHAR(40) NOT NULL,
    position VARCHAR(255),
    name VARCHAR(255),
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (proposal_id) REFERENCES purchase_request_proposals(id)
);

CREATE INDEX idx_purchase_request_proposal_approval_lines_proposal
    ON purchase_request_proposal_approval_lines(proposal_id, line_type, sort_order);
