#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${1:?usage: scripts/gcp/03_env_render/00_render-server-env.sh scripts/gcp/00_env/prod.env app|db}"
TARGET="${2:?target must be app or db}"
# shellcheck disable=SC1090
source "${ENV_FILE}"

DB_INTERNAL_IP_ACTUAL="$(gcloud compute addresses describe "${DB_INTERNAL_IP_NAME}" --project="${PROJECT_ID}" --region="${REGION}" --format='value(address)' 2>/dev/null || true)"
APP_INTERNAL_IP_ACTUAL="$(gcloud compute instances describe "${APP_INSTANCE_NAME}" --project="${PROJECT_ID}" --zone="${ZONE}" --format='value(networkInterfaces[0].networkIP)' 2>/dev/null || true)"
APP_STATIC_IP="$(gcloud compute addresses describe "${APP_STATIC_IP_NAME}" --project="${PROJECT_ID}" --region="${REGION}" --format='value(address)' 2>/dev/null || true)"
API_BASE_URL="${API_DOMAIN:+https://${API_DOMAIN}}"
if [[ -z "${API_BASE_URL}" && -n "${APP_STATIC_IP}" ]]; then
  API_BASE_URL="http://${APP_STATIC_IP}:8080"
fi
APP_DB_CIDR_ACTUAL="${APP_DB_CIDR:-}"
if [[ -z "${APP_DB_CIDR_ACTUAL}" && -n "${APP_INTERNAL_IP_ACTUAL}" ]]; then
  APP_DB_CIDR_ACTUAL="${APP_INTERNAL_IP_ACTUAL}/32"
fi
APP_DB_CIDR_ACTUAL="${APP_DB_CIDR_ACTUAL:-100.64.0.0/10}"
OTEL_TRACES_SAMPLER_ARG_DEFAULT=0.05
if [[ "${ENVIRONMENT}" == "dev" ]]; then
  OTEL_TRACES_SAMPLER_ARG_DEFAULT=1.0
fi

case "${TARGET}" in
  app)
    cat <<EOF
SPRING_PROFILES_ACTIVE=${ENVIRONMENT}
APP_PORT=8080
MANAGEMENT_PORT=9090
NODE_EXPORTER_PORT=9100
API_DOMAIN=${API_DOMAIN:-}
ENABLE_CADDY=${ENABLE_CADDY:-true}
TAILSCALE_TAGS=${APP_TAILSCALE_TAGS:-}
TAILSCALE_ACCEPT_DNS=${APP_TAILSCALE_ACCEPT_DNS:-false}
APP_LOG_DIR=./logs/app
LOG_FILE_PATTERN=./logs/app/application.%d{yyyy-MM-dd}.log
LOG_UPLOAD_PATH=./logs/app/application.*.log
LOG_FILE_LEVEL=${LOG_FILE_LEVEL:-WARN}
LOG_FILE_MAX_HISTORY=30
LOG_FILE_TOTAL_SIZE_CAP=1GB
LOG_LEVEL_ROOT=${LOG_LEVEL_ROOT:-WARN}
LOG_LEVEL_APP=${LOG_LEVEL_APP:-WARN}
LOG_LEVEL_SPRING=${LOG_LEVEL_SPRING:-WARN}
LOG_LEVEL_SQL=${LOG_LEVEL_SQL:-WARN}
CLOUD_LOGGING_ENABLED=true
CLOUD_LOGGING_LOG_ID=gjlearn-${ENVIRONMENT}-app
OTEL_JAVAAGENT_ENABLED=true
OTEL_SERVICE_NAME=guemjeongyahak-backend-${ENVIRONMENT}
OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-http://100.71.128.71:4318}
OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
OTEL_TRACES_EXPORTER=otlp
OTEL_METRICS_EXPORTER=none
OTEL_LOGS_EXPORTER=otlp
OTEL_TRACES_SAMPLER=parentbased_traceidratio
OTEL_TRACES_SAMPLER_ARG=${OTEL_TRACES_SAMPLER_ARG:-${OTEL_TRACES_SAMPLER_ARG_DEFAULT}}

POSTGRES_HOST=${DB_INTERNAL_IP_ACTUAL}
POSTGRES_PORT=5432
POSTGRES_DB=geumjeongyahak
POSTGRES_USER=postgres
POSTGRES_PASSWORD=CHANGE_ME
POSTGRES_OPTIONS=
FLYWAY_ENABLED=true
FLYWAY_BASELINE_ON_MIGRATE=false

ADMIN_BOOTSTRAP_ENABLED=true
ADMIN_EMAIL=admin@example.com
ADMIN_PASSWORD=CHANGE_ME_STRONG_12_CHARS_1A!
ADMIN_NAME=관리자

JWT_SECRET=CHANGE_ME_AT_LEAST_256_BITS
JWE_SECRET=CHANGE_ME_AT_LEAST_256_BITS
CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-${FRONTEND_ORIGIN}}

GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REDIRECT_URI=${API_BASE_URL}/api/v1/auth/google/callback
FRONTEND_BASE_URL=${FRONTEND_BASE_URL:-${FRONTEND_ORIGIN}}
FRONTEND_REDIRECT_URI=${FRONTEND_REDIRECT_URI}

MAIL_ENABLED=${MAIL_ENABLED:-false}
MAIL_FALLBACK_TO_LOG=${MAIL_FALLBACK_TO_LOG:-false}
MAIL_HOST=${MAIL_HOST:-smtp.mailersend.net}
MAIL_PORT=${MAIL_PORT:-587}
MAIL_USERNAME=${MAIL_USERNAME:-}
MAIL_PASSWORD=${MAIL_PASSWORD:-}
MAIL_SMTP_AUTH=${MAIL_SMTP_AUTH:-true}
MAIL_SMTP_STARTTLS_ENABLE=${MAIL_SMTP_STARTTLS_ENABLE:-true}
MAIL_FROM_EMAIL=${MAIL_FROM_EMAIL:-no-reply@example.com}
MAIL_FROM_NAME=${MAIL_FROM_NAME:-금정야학}
MAIL_PASSWORD_RESET_PATH=${MAIL_PASSWORD_RESET_PATH:-/auth/reset-password}
PASSWORD_RESET_EXPIRATION_MINUTES=${PASSWORD_RESET_EXPIRATION_MINUTES:-15}
MAIL_EMAIL_VERIFICATION_PATH=${MAIL_EMAIL_VERIFICATION_PATH:-/auth/email-verification}
EMAIL_VERIFICATION_EXPIRATION_MINUTES=${EMAIL_VERIFICATION_EXPIRATION_MINUTES:-15}

GCP_PROJECT_ID=${PROJECT_ID}
GCP_PROD_BUCKET_NAME=${STORAGE_BUCKET_NAME}
GCP_DEV_BUCKET_NAME=${STORAGE_BUCKET_NAME}
GCP_ENCODED_CREDENTIALS=
GOOGLE_DRIVE_SHARED_DRIVE_ID=${GOOGLE_DRIVE_SHARED_DRIVE_ID:-}
GOOGLE_DRIVE_MAKE_LINK_PUBLIC=${GOOGLE_DRIVE_MAKE_LINK_PUBLIC:-true}
GOOGLE_DRIVE_OAUTH_CLIENT_ID=${GOOGLE_DRIVE_OAUTH_CLIENT_ID:-}
GOOGLE_DRIVE_OAUTH_CLIENT_SECRET=${GOOGLE_DRIVE_OAUTH_CLIENT_SECRET:-}
GOOGLE_DRIVE_OAUTH_REFRESH_TOKEN=${GOOGLE_DRIVE_OAUTH_REFRESH_TOKEN:-}
GOOGLE_DRIVE_FOLDER_ID_HANDOVER=${GOOGLE_DRIVE_FOLDER_ID_HANDOVER:-}
GOOGLE_DRIVE_FOLDER_ID_EXAM_MATERIALS=${GOOGLE_DRIVE_FOLDER_ID_EXAM_MATERIALS:-}
GOOGLE_DRIVE_FOLDER_ID_DOCUMENT_FORMS=${GOOGLE_DRIVE_FOLDER_ID_DOCUMENT_FORMS:-}
GOOGLE_DRIVE_FOLDER_ID_MEETING_RECORDS=${GOOGLE_DRIVE_FOLDER_ID_MEETING_RECORDS:-}
GOOGLE_DRIVE_FOLDER_ID_BOARD=${GOOGLE_DRIVE_FOLDER_ID_BOARD:-}

FIREBASE_ENABLED=false
FIREBASE_PROJECT_ID=
FIREBASE_CREDENTIALS_BASE64=
FIREBASE_WEB_API_KEY=
FIREBASE_WEB_AUTH_DOMAIN=
FIREBASE_WEB_PROJECT_ID=
FIREBASE_WEB_STORAGE_BUCKET=
FIREBASE_WEB_MESSAGING_SENDER_ID=
FIREBASE_WEB_APP_ID=
FIREBASE_WEB_VAPID_KEY=
EOF
    ;;
  db)
    cat <<EOF
DB_PORT=5432
DB_LISTEN_ADDRESS=*
APP_DB_CIDR=${APP_DB_CIDR_ACTUAL}
NODE_EXPORTER_PORT=9100
POSTGRES_EXPORTER_PORT=9187
TAILSCALE_TAGS=${DB_TAILSCALE_TAGS:-}
TAILSCALE_ACCEPT_DNS=${DB_TAILSCALE_ACCEPT_DNS:-false}
POSTGRES_DB=geumjeongyahak
POSTGRES_USER=postgres
POSTGRES_PASSWORD=CHANGE_ME
EOF
    ;;
  *)
    echo "unknown target: ${TARGET}" >&2
    exit 1
    ;;
esac
